### ISSUE TITLE
monitor: metadata changed for messages service

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#108]
_**This issue was automatically created by the [knesset-data health monitor](https://github.com/hasadna/knesset-data/tree/master/python/knesset_data/dataservice/monitor), please do not modify the title or remove any labels**_

change detected in metadata of messages service

url=http://online.knesset.gov.il/WsinternetSps/KnessetDataService/KnessetMessagesData.svc

for more details see: https://gist.github.com/OriHoch/f62d7477f0a5243b6521a472305a04c9

**Comment by alonisser** [comment]
Only difference is encoding

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>

If this does not influence are code I think can be closed
