### ISSUE TITLE
monitor: metadata changed for lobbyists service

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#109]
_**This issue was automatically created by the [knesset-data health monitor](https://github.com/hasadna/knesset-data/tree/master/python/knesset_data/dataservice/monitor), please do not modify the title or remove any labels**_

change detected in metadata of lobbyists service

url=http://online.knesset.gov.il/WsinternetSps/KnessetDataService/LobbyistData.svc

for more details see: https://gist.github.com/OriHoch/35c1e3ef1ea528f966d1c234f507e9a4

**Comment by OriHoch** [comment]
_**Encountered the error again**_

change detected in metadata of lobbyists service

url=http://online.knesset.gov.il/WsinternetSps/KnessetDataService/LobbyistData.svc

for more details see: https://gist.github.com/OriHoch/2be5b92644c3bad4202d158a4d8ae2a4

**Comment by alonisser** [comment]
Only difference is encoding

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>

If this does not influence are code I think can be closed
