### ISSUE TITLE
monitor: metadata changed for bills service

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#110]
_**This issue was automatically created by the [knesset-data health monitor](https://github.com/hasadna/knesset-data/tree/master/python/knesset_data/dataservice/monitor), please do not modify the title or remove any labels**_

change detected in metadata of bills service

url=http://online.knesset.gov.il/WsinternetSps/KnessetDataService/BillsData.svc

for more details see: https://gist.github.com/OriHoch/198f78c413a716f49477fb9fd341f6bb

**Comment by alonisser** [comment]
@OriHoch looks like the only diff here is encoding (Moved from utf-8 to iso-8859-1)

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>

If this does not influence are code I think can be closed
