### ISSUE TITLE
Messages metadata api broken

### ISSUE THREAD

**Issue by alonisser** [hasadna/knesset-data#112]
http://online.knesset.gov.il/WsinternetSps/KnessetDataService/KnessetMessagesData.svc/
Messages api return the following xml:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<service xmlns:atom="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app" xmlns="http://www.w3.org/2007/app" xml:base="http://online.knesset.gov.il/WsinternetSps/KnessetDataService/KnessetMessagesData.svc/">
<workspace>
<atom:title>Default</atom:title>
<collection href="MessageSources">
<atom:title>MessageSources</atom:title>
</collection>
<collection href="Messages">
<atom:title>Messages</atom:title>
</collection>
</workspace>
</service>
```

But when traversing to the messages link
http://online.knesset.gov.il/WsinternetSps/KnessetDataService/KnessetMessagesData.svc/Messages

The request is stuck for a long time 
and then gets an error message:

```

Error: Server Error

The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.
```

The MessageResources link does work as expected

**Comment by OriHoch** [comment]
less relevant with the new API (opened an issue to review the old bugs and see if they reproduce in the new API - #131)
