### ISSUE TITLE
private laws suggested api (new api) breaks on skiptoken

### ISSUE THREAD

**Issue by alonisser** [hasadna/knesset-data#113]
Recreate:
navigate to:
http://knesset.gov.il/KnessetOdataService/LawsData.svc/privatelaw
search for <link> with rel=next
<link rel="next" href="http://knesset.gov.il/KnessetOdataService/LawsData.svc/privatelaw?$skiptoken=419" />
Navigate to href
http://knesset.gov.il/KnessetOdataService/LawsData.svc/privatelaw?$skiptoken=419

Get knesset error page:
http://www.knesset.gov.il/error_technical_problem.htm

**Comment by OriHoch** [comment]
less relevant with the new API (opened an issue to review the old bugs and see if they reproduce in the new API - #131)
