### ISSUE TITLE
New knesset API, some links return atom instead of xml as default break xodata explorer

### ISSUE THREAD

**Issue by alonisser** [hasadna/knesset-data#115]
http://knesset.gov.il/KnessetOdataService/LawsData.svc/
http://knesset.gov.il/KnessetOdataService/BillsData.svc/
http://knesset.gov.il/KnessetOdataService/FinalLawsData.svc/
http://knesset.gov.il/KnessetOdataService/VotesData.svc/
http://knesset.gov.il/KnessetOdataService/CommitteeScheduleData.svc/
http://knesset.gov.il/KnessetOdataService/MMMData.svc/
http://knesset.gov.il/KnessetOdataService/LobbyistODataService.svc/
http://knesset.gov.il/KnessetOdataService/KnessetMembersData.svc/

**Comment by OriHoch** [comment]
less relevant with the new API (opened an issue to review the old bugs and see if they reproduce in the new API - #131)
