### ISSUE TITLE
should have documentation regarding expected code formatting / logic guidelines / explanation about the repos

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#120]

**Comment by OriHoch** [comment]
#### How to decide where to move existing code from open knesset?
* You should always try to move as much as possible into the knesset-data pure python API - we should be as platform independent as possible.
* However, the python API only handles stateless data flow - it gets some data from 3rd party (AKA Knesset) and forwards it with some processing as an output stream
* code which requires a database or is too dependant on django infrastructure - should be in knesset-data-django
* knesset-data-django contains platform dependant code, which usually means access to the Open Knesset Django models or some other Django specific dependency

**Comment by OriHoch** [comment]
should consider all the knesset-data sub-projects: python / django / datapackage

**Comment by OriHoch** [comment]
linked to this issue from README

**Comment by alonisser** [comment]
Perhaps code formatting would be better served with an automated configuration file for code style check?

**Comment by OriHoch** [comment]
yes, that'll be great
