### ISSUE TITLE
משחק (אפליקציית ווב) המאפשר לנחש מספר פעמים בין שני נושאים אקראיים שבהם דנו יותר בכנסת (בריאות מול מעון רוה"מ, שחיתות מול תקשורת)

### ISSUE THREAD

**Issue by simonaho** [hasadna/knesset-data#139]
משחק (אפליקציית ווב ) המאפשר לנחש מספר פעמים בין שני נושאים אקראיים שבהם דנו יותר בכנסת (בריאות מול בטחון, שחיתות מול תקשורת)
המשחק יריץ 20 שאלות ויציג את הנקודות שנצברו עם אפשרות לשתף בפייסבוק

**Comment by OriHoch** [comment]
Issue moved to [hasadna/Open-Knesset #838](https://github.com/hasadna/Open-Knesset/issues/838) via [**ZenHub**](https://www.zenhub.com/)
