### ISSUE TITLE
trying to get all latest committee meetings doesn't return any meetings

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#14]
#### reproduction steps
- open url: http://online.knesset.gov.il/WsinternetSps/KnessetDataService/CommitteeScheduleData.svc/CommitteeAgendaSearch?FromDate=%272016-01-01T00:00:00%27
##### expected
- list of committee meetings since Jan 01, 2016
##### actual
- nothing is returned
  ![image](https://cloud.githubusercontent.com/assets/1198854/12873376/f19a0866-cdc3-11e5-9a94-f656f8bf2204.png)

**Comment by OriHoch** [comment]
Record of email correspondence with Knesset:

###### Sent: Feb 7, 2016 | From: @OriHoch
<p dir=rtl>
התחלנו להשתמש בממשק הנתונים החדש, יש עם הממשק בעיות רבות שמקשות לעבוד איתו באופן שוטף, להלן כמה מהן:
<ul><li>(link to this issue)</li></ul>
</p>

###### Sent: Feb 8, 2016 | From: Deputy Director of the Information Departmnet (סגן מנהל חטיבת המידע)
<p dir=rtl>
אנחנו מטפלים ברשימת הבקשות (תקלות) שציינת.
</p>

**Comment by OriHoch** [comment]
###### Sent: Feb 14, 2016 | From: Deputy Director of the Information Departmnet (סגן מנהל חטיבת המידע)
<p dir=rtl>
רשימת הישיבות פתוחות החל מה-01 לינואר 2016 ואילך קיימות ומעודכנות
            - מצרף דוגמא של ישיבת ועדת הכספים
            - קישור:   http://online.knesset.gov.il/WsinternetSps/KnessetDataService/CommitteeScheduleData.svc/CommitteeAgendaSearch?CommitteeId=%272%27&FromDate=%2701/01/2016%27&ToDate=%27%27&Subject
</p>

###### Sent: Feb 14, 2016 | From: @OriHoch
<p dir=rtl>
כל הפרטים נמצאים בקישורים ששלחתי

נראה שבתשובתכם התעלמתם לחלוטין מכל מה שכתוב בקישורים ששלחתי. אני יכול לחזור ולכתוב פה מה שכתוב שן אבל נראה לי קצת חסר טעם

בקישורים הנ"ל מופיעים כל הפרטים כולל כתובות מדויקות ותיאור של התקלות

אם עדיין לא ברור אשמח להוסיף מידע נוסף
</p>


###### Sent: Feb 14, 2016 | From: @OriHoch
<p dir=rtl>
רק שיהיה ברור - כל התקלות שתוארו במייל המקורי עדיין קיימות.
</p>

**Comment by OriHoch** [comment]
Knesset was notified today that we are still waiting for an answer

The following description was sent regarding this bug:

כשמנסים לשלוף מידע על ישיבות ועדה בלי לציין ועדה ספציפית לא מתקבלות תוצאות

**Comment by OriHoch** [comment]
###### Sent: Mar 6, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
יש הרבה באגים חמורים נוספים שעדיין לא החזרתם לנו תשובה לגביהם:
<br/>
(link to this bug)
</p>

**Comment by yotamsha** [comment]
@OriHoch 
התחלתי לעבוד היום עם הממשק נתונים של הכנסת היום במסגרת אי-פארט ובדיוק נתקלתי בבעיה
הזאת גם. אם אתה שומע על התקדמות בנושא אני אשמח לעדכון..

**Comment by morchickit** [comment]
יותם, אנחנו עובדים מול הכנסת כבר יותר משלושה שבועות ואין מענה בנושא. אני
אשמח אם תוכלו לתאם איתנו עבודה מולם ולראות איך נוכל לקדם את זה ביחד

**Comment by yotamsha** [comment]
אני אשמח, היה יכול להיות מצויין אם הם היו יכולים להיות חלק מהגיטהאב הזה ככה שכולנו נוכל
להיות מעודכנים אם יש איזו התקדמות. 
ממה שהבנתי אורי נמצא איתם בקשר ישיר. אם יש משהו שנוכל לעשות כדי לעזור לקדם את העבודה 
אתם יכולים לפנות אלי ישירות כאן או בטלפון.

**Comment by OriHoch** [comment]
we are now moving to the new knesset API so this issue is less relevant
