### ISSUE TITLE
there is no way to know which member voted on which vote (using the knesset dataservice api)

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#17]
the VotesData.svc/vote_rslts_kmmbr_shadow entity is supposed to show which member voted on which vote. But there is only a member id which appears like it's not linked to anywhere.

This entity should contain a field with member_id relating to KnessetMembersData.svc/View_mk_individual

**Comment by OriHoch** [comment]
Record of email correspondence with Knesset:

###### Sent: Feb 7, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
בגלל שאין תיעוד לממשק הנתונים אז אני לא יודע אם זה באג או שזה משהו שלא פותח.
בכל אופן, אנחנו רוצים למשוך נתוני הצבעות ונראה שאין דרך לדעת בדיוק איזה ח"כ הצביע ובאיזה אופן עבור כל הצבעה
להלן הבאג הרלוונטי במערכת שלנו
</p>

**Comment by Omerle** [comment]
take a look at this website:
https://oknesset.org/vote/652/
it seems like they could pull of who voted for what.
or are these votes in commitees and than there is another interface to work with?

the developer of the site I mentioned abouve is Yair Chucem and you can find it in my facebook friends
Omer Lewy

**Comment by OriHoch** [comment]
yes, I am a developer of Open Knesset :)
we are getting the votes from scraping the html of the votes page, you can see that scraper [here](https://github.com/hasadna/knesset-data/blob/master/python/knesset_data/html_scrapers/votes.py)

However, we want to stop using the html for the data and instead get it in a standard way using the official knesset API

**Comment by OriHoch** [comment]
###### Sent: Feb 22, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
 אני מזכיר שיש עדיין באג חמור בממשק ההצבעות שדיווחתי עליו לפני שבועיים ועדיין לא קיבלנו עליו תשובה כלשהי
<br/>
כרגע אין אפשרות לדעת את פילוח ההצבעה לפי כל ח"כ - ניתן לדעת רק את הסיכום של כמה הצביעו בעד/נגד אבל אין אפשרות לדעת איך כל ח"כ ספציפי הצביע או בכלל איזה ח"כים השתתפו בהצבעה
<br/>
הפרטים הטכניים נמצאים כאן:
<br/>
https://github.com/hasadna/knesset-data/issues/17
</p>

**Comment by OriHoch** [comment]
###### Sent: Mar 6, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
יש הרבה באגים חמורים נוספים שעדיין לא החזרתם לנו תשובה לגביהם:
<br/>
(link to this bug)
</p>

**Comment by OriHoch** [comment]
less relevant with the new API
