### ISSUE TITLE
Knesset Dataservice: ordering votes by date returns error

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#19]
#### Reproduction steps
* go to: [http://online.knesset.gov.il/WsinternetSps/KnessetDataService/VotesData.svc/View_vote_rslts_hdr_Approved?$top=20&$orderby=vote_date desc](http://online.knesset.gov.il/WsinternetSps/KnessetDataService/VotesData.svc/View_vote_rslts_hdr_Approved?$top=20&$orderby=vote_date desc)

##### Expected
* list of votes ordered by vote_date descending

##### Actual
* Error
* 
![image](https://cloud.githubusercontent.com/assets/1198854/13171578/34e1c532-d6fc-11e5-9f07-e28b892efa45.png)
* ![image](https://cloud.githubusercontent.com/assets/1198854/13171605/55ea749a-d6fc-11e5-87b9-131b97f9b479.png)

#### Notes
* This worked until a few days ago

**Comment by OriHoch** [comment]
###### Sent: Feb 19, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
ממשק הנתונים של ההצבעות לא מאפשר לנו לעשות מיון מה שמונע מאיתנו לעדכן את ההצבעות בכנסת פתוחה (בגלל שאין לנו אפשרות לקבל רק את ההצבעות החדשות ביותר)
<br/>
חשוב לציין שזה עבד עד לפני מספר ימים - מדובר בשינוי או בתקלה חדשה בצד שלכם
<br/>
נשמח לתיקון בהקדם
<br/>
כל הפרטים הטכניים נמצאים פה: 
<br/>
https://github.com/hasadna/knesset-data/issues/19
</p>

**Comment by OriHoch** [comment]
related open knesset issue: https://github.com/hasadna/Open-Knesset/issues/549

**Comment by OriHoch** [comment]
###### Sent: Feb 19, 2016 | From: Deputy Director of the Information Departmnet (סגן מנהל חטיבת המידע)
<p dir=rtl>
נבדוק את נושא ההצבעות כפי שתארת והקושי במיון.
</p>

**Comment by OriHoch** [comment]
###### Sent: Feb 19, 2016 | From: @OriHoch  To: Deputy Director of the Information Departmnet (סגן מנהל חטיבת המידע)
<p dir=rtl>
תודה רבה, רק חשוב לציין שלא מדובר בקושי במיון אלא שאין אפשרות בכלל לבצע מיון
</p>

**Comment by alonisser** [comment]
Looks like just been solved, I got an error and two minutes later everything was working again

**Comment by OriHoch** [comment]
@alonisser - still doesn't work for me, could you check again please?
we are talking about this URL (with the orderby parameter):
[http://online.knesset.gov.il/WsinternetSps/KnessetDataService/VotesData.svc/View_vote_rslts_hdr_Approved?$top=20&$orderby=vote_date desc](http://online.knesset.gov.il/WsinternetSps/KnessetDataService/VotesData.svc/View_vote_rslts_hdr_Approved?$top=20&$orderby=vote_date desc)

**Comment by alonisser** [comment]
Stopped working again.. something flaky there

**Comment by OriHoch** [comment]
###### Sent: Feb 22, 2016 | From: Deputy Director of the Information Departmnet (סגן מנהל חטיבת המידע)
<p dir=rtl>
בממשק הנתונים של ההצבעות התרחשה תקלה, ולא מדובר בשינוי יזום,
<br/>
מעדכן שהתקלה תוקנה.
</p>

**Comment by OriHoch** [comment]
looks like it's fixed
