### ISSUE TITLE
Knesset Dataservice: filtering by date returns an error in votes and MMM services

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#20]
#### Reproduction Steps (for votes)
- make a request to get votes data and add a filtering on the vote_date field
- for example: [http://online.knesset.gov.il/WsinternetSps/KnessetDataService/VotesData.svc/View_vote_rslts_hdr_Approved?$top=50&$filter=vote_date gt datetime'2014-01-01T00:00:00' and vote_date lt datetime'2014-02-01T00:00:00'](http://online.knesset.gov.il/WsinternetSps/KnessetDataService/VotesData.svc/View_vote_rslts_hdr_Approved?$top=50&$filter=vote_date gt datetime'2014-01-01T00:00:00' and vote_date lt datetime'2014-02-01T00:00:00')
##### Expected
- list of votes filtered according to the $filter
- in the above example, I expect to get votes between 01, Jan, 2014 and 01, Feb, 2014
##### Actual
- Error
- 
  ![image](https://cloud.githubusercontent.com/assets/1198854/13220606/c156e670-d97f-11e5-9e5a-1e4c177e0615.png)
- 
  ![image](https://cloud.githubusercontent.com/assets/1198854/13220630/d5468ee2-d97f-11e5-976c-c2e102c401fa.png)
##### Additional scenarios
- the same occurs with MMM data service - see comment by @alonisser below

**Comment by OriHoch** [comment]
###### Sent: Feb 22, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
בשליפת נתונים של הצבעות - אם מנסים לבצע חיפוש לפי תאריך אנחנו מקבלים שגיאה
</p>

**Comment by alonisser** [comment]
This also happens on the mmm api

http://online.knesset.gov.il/WsinternetSps/KnessetDataService/MMMData.svc/View_documents?$top=100&$filter=doc_date%20gt%20datetime%272014-01-01T00:00:00%27&$orderby=doc_date%20desc&$select=doc_abstract,doc_date,doc_id,doc_link,DocumentsDocumentClient&$expand=DocumentsDocumentClient

**Comment by OriHoch** [comment]
###### Sent: Feb 28, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
התקלה מתרחשת גם בשירות של מסמכי ממ"מ - כל הפרטים מעודכנים בקישור:
<br/>
https://github.com/hasadna/knesset-data/issues/20
</p>

**Comment by OriHoch** [comment]
###### Sent: Mar 6, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
יש הרבה באגים חמורים נוספים שעדיין לא החזרתם לנו תשובה לגביהם:
<br/>
(link to this bug)
</p>

**Comment by OriHoch** [comment]
less relevant with the new knesset API
