### ISSUE TITLE
Knesset Dataservice: wrong vote total against count returned for vote id 22156

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#22]
#### Reproduction Steps
- Open vote id 22156 on Knesset website: http://www.knesset.gov.il/vote/heb/Vote_Res_Map.asp?vote_id_t=22156
- note the number of votes against is 4 (both in the total number and if you add up the separate votes)
- Open the same vote in DataService: [http://online.knesset.gov.il/WsinternetSps/KnessetDataService/VotesData.svc/View_vote_rslts_hdr_Approved?$top=20&$filter=vote_id eq 22156](http://online.knesset.gov.il/WsinternetSps/KnessetDataService/VotesData.svc/View_vote_rslts_hdr_Approved?$top=20&$filter=vote_id eq 22156)
- look at the value for "total_against" property
##### Expected
- total against should be 4 (as it is on the website)
##### Actual
- total against is 3
- ![image](https://cloud.githubusercontent.com/assets/1198854/13253762/6fd5a972-da46-11e5-8c09-11464c00c2e0.png)

**Comment by OriHoch** [comment]
###### Sent: Feb 23, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
גילינו באג חמור בנתוני ההצבעות שבו ממשק הנתונים מציג עבור הצבעה שסה"כ 3 ח"כים הצביעו נגד אבל באתר מופיע ש-4 ח"כים הצביעו נגד.
<br/>
הבאג הזה מדאיג מאוד, חייבים לוודא שהנתונים שהממשק מחזיר נכונים אחרת לא נוכל להשתמש בו. 
</p>

**Comment by OriHoch** [comment]
###### Sent: Feb 23, 2016 | From: Deputy Director of the Information Departmnet (סגן מנהל חטיבת המידע)
<p dir=rtl>
כל ההצבעות במליאת הכנסת נבדקות בצורה פרטנית, כך שכל הצבעה עוברת לבדיקה של ארכיון הכנסת לצורך טיוב.
<br/>
הטיוב עצמו נעשה מול פרוטוקול מליאת הכנסת ואם נדרש גם בעזרת וידיאו.
<br/>
במקרה ונמצאו פערים, נשמרים כל הנתונים, שהם ההצבעה המקורית, ביצוע התיקון ותוצאות ההצבעה הרשמיות.
<br/>
מכאן, לשאלתך, חטיבת המידע מוודאת שהנתונים מדויקים.
<br/>
באשר לנתונים של הממשק, נערכת בדיקה עם אגף הטכנולוגיה לגבי אופן הצגת הנתונים בממשק זה.
<br/>
תודה על הדוגמה ואשלח עדכון.
</p>

**Comment by OriHoch** [comment]
###### Sent: Mar 6, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
יש הרבה באגים חמורים נוספים שעדיין לא החזרתם לנו תשובה לגביהם:
<br/>
(link to this bug)
</p>

**Comment by alonisser** [comment]
התכתבות חדשה עם שי ברקוביץ טכנולוג ראשי בנושא הבאג הזה
נראה שב API משנה אחר יש נתונים נכונים 
רק לא בסכימה
http://knesset.gov.il/KnessetOdataService/VotesData.svc/vote_rslts_kmmbr_shadow()?$filter=vote_id%20eq%2022156

**Comment by OriHoch** [comment]
less relevant with the new knesset API
