### ISSUE TITLE
MMM dataservice is extremely  flaky (at best)

### ISSUE THREAD

**Issue by alonisser** [hasadna/knesset-data#29]
for example trying the following (url encoded) url:

```
http://online.knesset.gov.il/WsinternetSps/KnessetDataService/MMMData.svc/View_documents?orderBy=doc_date+desc&skip=0&top=10&%24select=doc_abstract%2Cdoc_date%2Cdoc_id%2Cdoc_link%2CDocumentsDocumentClient&%24expand=DocumentsDocumentClient
```

Completely valid odata request and validated with xodata

fails 8 out 10 times and sometimes all the time (for example 5.3.16 19:00 Israel time)
When trying without any params it does work quite consistently.

Interesting Info that might be connected to the issue: dataServiceVersion header is different with mmm then from Votes and Meetings. returns 2.0 and not 1.0 as the Votes And Meetings APIs.

Blocks adding mmm data #24

**Comment by OriHoch** [comment]
###### Sent: Mar 6, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
להלן באגים חמורים שמונעים שימוש בממשקי הנתונים של לוביסטים וממ"מ:
<br/>
ממשק הנתונים של ממ"מ מחזיר שגיאות לעיתים תכופות: https://github.com/hasadna/knesset-data/issues/29
</p>

**Comment by OriHoch** [comment]
will be handled in #24 - need to check the new API
