### ISSUE TITLE
lobbyist hebrew data is returned as ?????

### ISSUE THREAD

**Issue by alonisser** [hasadna/knesset-data#30]
When trying the api for vie lobbyist represent

```
http://online.knesset.gov.il/WsinternetSps/KnessetDataService/LobbyistData.svc/View_lobbyist_represent/
```

I get for example:

``` xml
m:properties>
                <d:lobbyist_represent_id m:type="Edm.Int32">14821531</d:lobbyist_represent_id>
                <d:lobbyist_id m:type="Edm.Int32">205</d:lobbyist_id>
                <d:lobbyist_represent_name>??????</d:lobbyist_represent_name>
                <d:lobbyist_represent_domain>????÷??</d:lobbyist_represent_domain>
                <d:lobbyist_represent_type>÷???</d:lobbyist_represent_type>

            </m:properties>
```

**Comment by OriHoch** [comment]
###### Sent: Mar 6, 2016 | From: @OriHoch  To: Knesset Contact
<p dir=rtl>
להלן באגים חמורים שמונעים שימוש בממשקי הנתונים של לוביסטים וממ"מ:
<br/>
ממשק הנתונים של הלוביסטים מחזיר סימני שאלה: https://github.com/hasadna/knesset-data/issues/30 
</p>

**Comment by alonisser** [comment]
Looks working now. I'll monitor and update

**Comment by OriHoch** [comment]
I think we ran into this in the past as well, perhaps we should detect this and raise an exception so that we would be notified about it when the lobbyists scraper runs in open knesset

**Comment by alonisser** [comment]
Closing looks working in the new api
http://knesset.gov.il/KnessetOdataService/LobbyistODataService.svc
