### ISSUE TITLE
Knesset votes page in Open Knesset is not up to date

### ISSUE THREAD

**Issue by HovavYannai** [hasadna/knesset-data#32]
אהלן,
ההצבעות בכנסת פתוחה ישנות יחסית. החדשות ביותר הן מהשני בחודש מרץ.
עד כמה שהבנתי יש בעיה בגריפת המידע מאתר הכנסת. האם ההצבעות החדשות יעלו לאתר כנסת פתוחה?
תודה,
חובב
המשמר החברתי

**Comment by OriHoch** [comment]
Thanks for the bug report, This project (knesset-data) is not specific to open knesset, if you have bugs about open knesset, you should open them in Open-Knesset project.

I opened this bug for you there:
https://github.com/hasadna/Open-Knesset/issues/642
