### ISSUE TITLE
should have a knesset dataservice health monitor

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#4]
## User Story

Open Knesset periodically (every night) gets votes data form The Knesset using the [Knesset Dataservice](https://github.com/hasadna/knesset-data/blob/master/python/knesset_data/dataservice/README.md). 

On March. 2 there was a problem on Knesset side which caused votes api to stop working
#### Expected
- On March.3 - Open Knesset developers team are notified of the problem. They proceed to investigate and notify Knesset about the problem.
#### Actual
- Open Knesset developers were notified about the problem only on March.28 when someone manually noticed there is a problem (see hasadna/Open-Knesset#642)
## Description

should have a process that periodically (daily) checks the knesset dataservice services and automatically open new issues if problems are encountered

it should check:
- general availability of the service
- that latest data is returned
- that returned data is valid

**Comment by OriHoch** [comment]
this could be a python command that will run periodically via cron

this command should:
* iterate over the data services and fetch some data from  the knesset for each method
* generate a report of it's findings (whether it worked and returns the expected data)

**Comment by daonb** [comment]
What's the base? py.test?

**Comment by OriHoch** [comment]
whatever you wish.. open to suggestions

**Comment by bennybauer** [comment]
@OriHoch Hi, I'm hasadna newbie. This issue should be pretty straightforward and i'd like to help. 

Where the health check can be deployed? Does Hasadna have any budget for compute resources (AWS, Heroku, etc...)?

I've noticed that there's already [code](https://github.com/hasadna/knesset-data/blob/master/python/knesset_data/dataservice/monitor/metadata/periodic.py) for the check. IS anything missing there?

Thanks,
Benny

**Comment by OriHoch** [comment]
thanks, the metadata check code you linked to is a service that checks the metadata about the knesset services. not the data itself

this issue is about something similar that will check the data itself for any inconsistencies. at the most basic level it will check if the service returns http status 200 or not, more advanced stuff will be to open the data itself and use some kind of heuristics to determine if it's valid or not.

regarding deployment - we have everything needed to deploy this service. This issues should just be a python command which we will run somehow / somewhere

**Comment by bennybauer** [comment]
For fast solution, checking only the http status code, we can use a service like [StatusCake](statuscake.com), the free tier will be sufficient for this. Basically this is it: http://uptime.statuscake.com/?TestID=IEdmFQLe1V (I've created it on my free account, we should create an account for hasadna).

It has nice integrations, so when one of the endpoints is down you can trigger email, Slack, public tweet (could be nice!). If needed, it's possible to plug the email or slack to create a github issue. BTW, slack [should be free](https://slack.com/pricing#slack_for_good) for non profit orgs.

WDYT?

**Comment by OriHoch** [comment]
Sounds good

**Comment by bennybauer** [comment]
So how do we take it from here? 

1. What should be the strategy for endpoint downtime handling? Open a github issue, or just sending a link to the dashboard? What should be the distribution list? 
2. Is there a slack team? do we want one?

**Comment by OriHoch** [comment]
Yes we have slack , I'll invite you

**Comment by OriHoch** [comment]
@bennybauer - please send me you email, you can send me in twitter

**Comment by uda** [comment]
@OriHoch and @bennybauer 

1. I should be able to get from slack the NPO upgrade after I fill in the form
2. I created an account with status cake, but they don't seem to have NPO discounts.

So we can either save the tests for status cake in a repo and update via api
https://www.statuscake.com/api/
Or, we keep the enterprise solutions for infrastructure monitoring, and provide an organization wide instance like Zabbix
http://www.zabbix.com/license.php

**Comment by OriHoch** [comment]
personally I like the option of calling statuscake api from our server

**Comment by bennybauer** [comment]
@uda , 
1. maybe @morchickit is already on the slack NPO, better check with her
2. I prefer statuscake (or any other hosted solution) on maintaining Zabbix :)

If we're going on with statuscake please send me the credentials over slack and I'll handle this issue.

**Comment by OriHoch** [comment]
too much changed since this issue was opened, it's less relevant now that we use the datapackages
