### ISSUE TITLE
should have documentation of the available knesset data

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#5]
## User Story

Jack is a statistician that wants to do some research on the votes of the knesset. He searches google for knesset votes data and finds the knesset-data project. He uses the python apis to get all the raw data of votes he required for his researchh. He publishes his research based on the findings
### Expected
- Jack will achieve praise for his wonderful research
### Actual
- Jack will be scorned by his peers because he misused the data.
- Jack assumed that the field "total_against" contains the total number of members that voted against. 
- However - if Jack would have searched in the knesset-data issues he would have found issue #22 which mentions that total_against field is actually wrong in many cases.
## Description

We should have good documentation of the meaning of the data. This should not include just how to use the APIs but should give a description of the data - where the data is coming from, what's the meaning of the data, how often it's updated etc..

An example of such a documentation:

https://github.com/hasadna/knesset-data/blob/master/python/knesset_data/dataservice/VOTES.md
## See Also
- #31 - add sphinx docs

**Comment by OriHoch** [comment]
@noamelf @shevyk 
I'll take the laws dataservice

**Comment by OriHoch** [comment]
@neuhofmo (Moran) and Dana will take the members service

**Comment by maryLoi** [comment]
מה קורה עם המשימה? צריך עדין לעשות? איזה סוג של מומחיות זה מצריך?

**Comment by OriHoch** [comment]
now with the new knesset API and documentation they published it's less relevant

**Comment by alefbt** [comment]
@OriHoch , Can you share link for a reference of the API documentation ?

**Comment by OriHoch** [comment]
the documentation of knesset data sources is available [here](https://github.com/hasadna/knesset-data/blob/master/docs/DataSources.md)

specifically in this issue I guess you refer to the [dataservice docs](https://github.com/hasadna/knesset-data/blob/master/docs/dataservice/README.md)

Feel free to open an issue in this repository (knesset-data) with any questions or more details about your specific use-case for the data and I'll see if we can help
