### ISSUE TITLE
laws dataservice link field should contain full url or provide documentation on how to use to get the file

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data#69]
### reproduction steps
- open http://online.knesset.gov.il/WsinternetSps/KnessetDataService/LawsData.svc/privatelaw(318)
- look at the d:plaw_link field
##### expected
- field should contain full url to download the file
- (alternatively - provide documentation about how to use the link to get the file)
##### actual
- field contains just the file name without full url or any details about how to get the file
- see
  ![image](https://cloud.githubusercontent.com/assets/1198854/15627391/f523e2da-24ea-11e6-83f1-a7fab4025863.png)

**Comment by OriHoch** [comment]
Knesset was notified on May 29, 2016

**Comment by alonisser** [comment]
Still broken:
http://knesset.gov.il/KnessetOdataService/LawsData.svc/privatelaw(318)

**Comment by OriHoch** [comment]
less relevant with the new API (opened an issue to review the old bugs and see if they reproduce in the new API - #131)
